apiVersion: v1
kind: Service
metadata:
  name: presto-coordinator
spec:
  ports:
    - name: client
      port: 8080
  selector:
    app: presto-coordinator
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: presto-coordinator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: presto-coordinator
    spec:
      containers:
        - name: presto-coordinator
          image: asifkazi/prestodb
          imagePullPolicy: Always
          env:
            - name:  PRESTO_JVM_HEAP_SIZE 
              value: "4"
          ports:
            - containerPort: 8080
            - containerPort: 8889
          resources:
            requests:
              memory: "4Gi"
            limits:
              memory: "4Gi"
