---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:      
      - name: mysql
        image: mysql:5.7
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: Passw0rd
        - name: MYSQL_DATABASE
          value: sampledb
        - name: MYSQL_USER
          value: mysql
          # Use secret in real usage
        - name: MYSQL_PASSWORD
          value: Passw0rd
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        resources: 
          limits:
            memory: "128Mi"
            cpu: "500m"

      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  storageClassName: presto-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi


