apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: presto-sc
provisioner: spectrumscale.csi.ibm.com
parameters:
    volBackendFs: "scale-jmasc-csplab-cnsa-fs2"
    clusterId: "7190932967857929650"
    uid: "1000"
    gid: "1000"
reclaimPolicy: Delete
