apiVersion: v1
kind: ReplicationController
metadata:
  name: presto-worker
spec:
  replicas: 2 #16
  template:
    metadata:
      labels:
        app: presto
    spec:
      containers:
        - name: presto-worker
          image: asifkazi/prestodb
          imagePullPolicy: Always
          env:
             name: PRESTO_JVM_HEAP_SIZE
              value: "4"
          resources:
            requests:
              memory: "4Gi"
            limits:
              memory: "4Gi"
          ports:
            - containerPort: 8889
