apiVersion: v1
kind: ReplicationController
metadata:
  name: presto-worker
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: presto-worker
    spec:
      containers:
        - name: presto-worker
          image: asifkazi/presto-on-docker
          imagePullPolicy: Always
          env:
            - name: PRESTO_CONF_COORDINATOR
              value: "false"
            - name:  PRESTO_CONF_DISCOVERY_URI
              value: "http://presto-coordinator:8080"
          resources:
            requests:
              memory: "8Gi"
            limits:
              memory: "8Gi"
          ports:
            - containerPort: 8889
